/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: blockchain.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "blockchain.pb-c.h"
void   blockchain__transaction__init
                     (Blockchain__Transaction         *message)
{
  static const Blockchain__Transaction init_value = BLOCKCHAIN__TRANSACTION__INIT;
  *message = init_value;
}
size_t blockchain__transaction__get_packed_size
                     (const Blockchain__Transaction *message)
{
  assert(message->base.descriptor == &blockchain__transaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blockchain__transaction__pack
                     (const Blockchain__Transaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blockchain__transaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blockchain__transaction__pack_to_buffer
                     (const Blockchain__Transaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blockchain__transaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blockchain__Transaction *
       blockchain__transaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blockchain__Transaction *)
     protobuf_c_message_unpack (&blockchain__transaction__descriptor,
                                allocator, len, data);
}
void   blockchain__transaction__free_unpacked
                     (Blockchain__Transaction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blockchain__transaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blockchain__block_header__init
                     (Blockchain__BlockHeader         *message)
{
  static const Blockchain__BlockHeader init_value = BLOCKCHAIN__BLOCK_HEADER__INIT;
  *message = init_value;
}
size_t blockchain__block_header__get_packed_size
                     (const Blockchain__BlockHeader *message)
{
  assert(message->base.descriptor == &blockchain__block_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blockchain__block_header__pack
                     (const Blockchain__BlockHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blockchain__block_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blockchain__block_header__pack_to_buffer
                     (const Blockchain__BlockHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blockchain__block_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blockchain__BlockHeader *
       blockchain__block_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blockchain__BlockHeader *)
     protobuf_c_message_unpack (&blockchain__block_header__descriptor,
                                allocator, len, data);
}
void   blockchain__block_header__free_unpacked
                     (Blockchain__BlockHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blockchain__block_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blockchain__block__init
                     (Blockchain__Block         *message)
{
  static const Blockchain__Block init_value = BLOCKCHAIN__BLOCK__INIT;
  *message = init_value;
}
size_t blockchain__block__get_packed_size
                     (const Blockchain__Block *message)
{
  assert(message->base.descriptor == &blockchain__block__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blockchain__block__pack
                     (const Blockchain__Block *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blockchain__block__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blockchain__block__pack_to_buffer
                     (const Blockchain__Block *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blockchain__block__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blockchain__Block *
       blockchain__block__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blockchain__Block *)
     protobuf_c_message_unpack (&blockchain__block__descriptor,
                                allocator, len, data);
}
void   blockchain__block__free_unpacked
                     (Blockchain__Block *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blockchain__block__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blockchain__space_proof__init
                     (Blockchain__SpaceProof         *message)
{
  static const Blockchain__SpaceProof init_value = BLOCKCHAIN__SPACE_PROOF__INIT;
  *message = init_value;
}
size_t blockchain__space_proof__get_packed_size
                     (const Blockchain__SpaceProof *message)
{
  assert(message->base.descriptor == &blockchain__space_proof__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blockchain__space_proof__pack
                     (const Blockchain__SpaceProof *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blockchain__space_proof__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blockchain__space_proof__pack_to_buffer
                     (const Blockchain__SpaceProof *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blockchain__space_proof__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blockchain__SpaceProof *
       blockchain__space_proof__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blockchain__SpaceProof *)
     protobuf_c_message_unpack (&blockchain__space_proof__descriptor,
                                allocator, len, data);
}
void   blockchain__space_proof__free_unpacked
                     (Blockchain__SpaceProof *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blockchain__space_proof__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blockchain__challenge__init
                     (Blockchain__Challenge         *message)
{
  static const Blockchain__Challenge init_value = BLOCKCHAIN__CHALLENGE__INIT;
  *message = init_value;
}
size_t blockchain__challenge__get_packed_size
                     (const Blockchain__Challenge *message)
{
  assert(message->base.descriptor == &blockchain__challenge__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blockchain__challenge__pack
                     (const Blockchain__Challenge *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blockchain__challenge__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blockchain__challenge__pack_to_buffer
                     (const Blockchain__Challenge *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blockchain__challenge__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blockchain__Challenge *
       blockchain__challenge__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blockchain__Challenge *)
     protobuf_c_message_unpack (&blockchain__challenge__descriptor,
                                allocator, len, data);
}
void   blockchain__challenge__free_unpacked
                     (Blockchain__Challenge *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blockchain__challenge__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blockchain__transaction_batch__init
                     (Blockchain__TransactionBatch         *message)
{
  static const Blockchain__TransactionBatch init_value = BLOCKCHAIN__TRANSACTION_BATCH__INIT;
  *message = init_value;
}
size_t blockchain__transaction_batch__get_packed_size
                     (const Blockchain__TransactionBatch *message)
{
  assert(message->base.descriptor == &blockchain__transaction_batch__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blockchain__transaction_batch__pack
                     (const Blockchain__TransactionBatch *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blockchain__transaction_batch__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blockchain__transaction_batch__pack_to_buffer
                     (const Blockchain__TransactionBatch *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blockchain__transaction_batch__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blockchain__TransactionBatch *
       blockchain__transaction_batch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blockchain__TransactionBatch *)
     protobuf_c_message_unpack (&blockchain__transaction_batch__descriptor,
                                allocator, len, data);
}
void   blockchain__transaction_batch__free_unpacked
                     (Blockchain__TransactionBatch *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blockchain__transaction_batch__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blockchain__block_list__init
                     (Blockchain__BlockList         *message)
{
  static const Blockchain__BlockList init_value = BLOCKCHAIN__BLOCK_LIST__INIT;
  *message = init_value;
}
size_t blockchain__block_list__get_packed_size
                     (const Blockchain__BlockList *message)
{
  assert(message->base.descriptor == &blockchain__block_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blockchain__block_list__pack
                     (const Blockchain__BlockList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blockchain__block_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blockchain__block_list__pack_to_buffer
                     (const Blockchain__BlockList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blockchain__block_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blockchain__BlockList *
       blockchain__block_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blockchain__BlockList *)
     protobuf_c_message_unpack (&blockchain__block_list__descriptor,
                                allocator, len, data);
}
void   blockchain__block_list__free_unpacked
                     (Blockchain__BlockList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blockchain__block_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blockchain__pool_status__init
                     (Blockchain__PoolStatus         *message)
{
  static const Blockchain__PoolStatus init_value = BLOCKCHAIN__POOL_STATUS__INIT;
  *message = init_value;
}
size_t blockchain__pool_status__get_packed_size
                     (const Blockchain__PoolStatus *message)
{
  assert(message->base.descriptor == &blockchain__pool_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blockchain__pool_status__pack
                     (const Blockchain__PoolStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blockchain__pool_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blockchain__pool_status__pack_to_buffer
                     (const Blockchain__PoolStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blockchain__pool_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blockchain__PoolStatus *
       blockchain__pool_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blockchain__PoolStatus *)
     protobuf_c_message_unpack (&blockchain__pool_status__descriptor,
                                allocator, len, data);
}
void   blockchain__pool_status__free_unpacked
                     (Blockchain__PoolStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blockchain__pool_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blockchain__network_message__init
                     (Blockchain__NetworkMessage         *message)
{
  static const Blockchain__NetworkMessage init_value = BLOCKCHAIN__NETWORK_MESSAGE__INIT;
  *message = init_value;
}
size_t blockchain__network_message__get_packed_size
                     (const Blockchain__NetworkMessage *message)
{
  assert(message->base.descriptor == &blockchain__network_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blockchain__network_message__pack
                     (const Blockchain__NetworkMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blockchain__network_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blockchain__network_message__pack_to_buffer
                     (const Blockchain__NetworkMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blockchain__network_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blockchain__NetworkMessage *
       blockchain__network_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blockchain__NetworkMessage *)
     protobuf_c_message_unpack (&blockchain__network_message__descriptor,
                                allocator, len, data);
}
void   blockchain__network_message__free_unpacked
                     (Blockchain__NetworkMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blockchain__network_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blockchain__wallet__init
                     (Blockchain__Wallet         *message)
{
  static const Blockchain__Wallet init_value = BLOCKCHAIN__WALLET__INIT;
  *message = init_value;
}
size_t blockchain__wallet__get_packed_size
                     (const Blockchain__Wallet *message)
{
  assert(message->base.descriptor == &blockchain__wallet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blockchain__wallet__pack
                     (const Blockchain__Wallet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blockchain__wallet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blockchain__wallet__pack_to_buffer
                     (const Blockchain__Wallet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blockchain__wallet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blockchain__Wallet *
       blockchain__wallet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blockchain__Wallet *)
     protobuf_c_message_unpack (&blockchain__wallet__descriptor,
                                allocator, len, data);
}
void   blockchain__wallet__free_unpacked
                     (Blockchain__Wallet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blockchain__wallet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blockchain__difficulty_state__init
                     (Blockchain__DifficultyState         *message)
{
  static const Blockchain__DifficultyState init_value = BLOCKCHAIN__DIFFICULTY_STATE__INIT;
  *message = init_value;
}
size_t blockchain__difficulty_state__get_packed_size
                     (const Blockchain__DifficultyState *message)
{
  assert(message->base.descriptor == &blockchain__difficulty_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blockchain__difficulty_state__pack
                     (const Blockchain__DifficultyState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blockchain__difficulty_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blockchain__difficulty_state__pack_to_buffer
                     (const Blockchain__DifficultyState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blockchain__difficulty_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blockchain__DifficultyState *
       blockchain__difficulty_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blockchain__DifficultyState *)
     protobuf_c_message_unpack (&blockchain__difficulty_state__descriptor,
                                allocator, len, data);
}
void   blockchain__difficulty_state__free_unpacked
                     (Blockchain__DifficultyState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blockchain__difficulty_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor blockchain__transaction__field_descriptors[7] =
{
  {
    "nonce",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Transaction, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expiry_block",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Transaction, expiry_block),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source_address",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Transaction, source_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dest_address",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Transaction, dest_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Transaction, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fee",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Transaction, fee),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Transaction, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blockchain__transaction__field_indices_by_name[] = {
  3,   /* field[3] = dest_address */
  1,   /* field[1] = expiry_block */
  5,   /* field[5] = fee */
  0,   /* field[0] = nonce */
  6,   /* field[6] = signature */
  2,   /* field[2] = source_address */
  4,   /* field[4] = value */
};
static const ProtobufCIntRange blockchain__transaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor blockchain__transaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blockchain.Transaction",
  "Transaction",
  "Blockchain__Transaction",
  "blockchain",
  sizeof(Blockchain__Transaction),
  7,
  blockchain__transaction__field_descriptors,
  blockchain__transaction__field_indices_by_name,
  1,  blockchain__transaction__number_ranges,
  (ProtobufCMessageInit) blockchain__transaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blockchain__block_header__field_descriptors[11] =
{
  {
    "previous_hash",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Blockchain__BlockHeader, previous_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hash",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Blockchain__BlockHeader, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__BlockHeader, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Blockchain__BlockHeader, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "farmer_address",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Blockchain__BlockHeader, farmer_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "difficulty",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__BlockHeader, difficulty),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "challenge_hash",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Blockchain__BlockHeader, challenge_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proof_hash",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Blockchain__BlockHeader, proof_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proof_nonce",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__BlockHeader, proof_nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quality",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Blockchain__BlockHeader, quality),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transaction_count",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__BlockHeader, transaction_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blockchain__block_header__field_indices_by_name[] = {
  6,   /* field[6] = challenge_hash */
  5,   /* field[5] = difficulty */
  4,   /* field[4] = farmer_address */
  1,   /* field[1] = hash */
  2,   /* field[2] = height */
  0,   /* field[0] = previous_hash */
  7,   /* field[7] = proof_hash */
  8,   /* field[8] = proof_nonce */
  9,   /* field[9] = quality */
  3,   /* field[3] = timestamp */
  10,   /* field[10] = transaction_count */
};
static const ProtobufCIntRange blockchain__block_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor blockchain__block_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blockchain.BlockHeader",
  "BlockHeader",
  "Blockchain__BlockHeader",
  "blockchain",
  sizeof(Blockchain__BlockHeader),
  11,
  blockchain__block_header__field_descriptors,
  blockchain__block_header__field_indices_by_name,
  1,  blockchain__block_header__number_ranges,
  (ProtobufCMessageInit) blockchain__block_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blockchain__block__field_descriptors[3] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Block, header),
    &blockchain__block_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transactions",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blockchain__Block, n_transactions),
    offsetof(Blockchain__Block, transactions),
    &blockchain__transaction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_fees",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Block, total_fees),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blockchain__block__field_indices_by_name[] = {
  0,   /* field[0] = header */
  2,   /* field[2] = total_fees */
  1,   /* field[1] = transactions */
};
static const ProtobufCIntRange blockchain__block__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor blockchain__block__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blockchain.Block",
  "Block",
  "Blockchain__Block",
  "blockchain",
  sizeof(Blockchain__Block),
  3,
  blockchain__block__field_descriptors,
  blockchain__block__field_indices_by_name,
  1,  blockchain__block__number_ranges,
  (ProtobufCMessageInit) blockchain__block__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blockchain__space_proof__field_descriptors[4] =
{
  {
    "plot_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Blockchain__SpaceProof, plot_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__SpaceProof, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proof_hash",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Blockchain__SpaceProof, proof_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quality",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Blockchain__SpaceProof, quality),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blockchain__space_proof__field_indices_by_name[] = {
  1,   /* field[1] = nonce */
  0,   /* field[0] = plot_id */
  2,   /* field[2] = proof_hash */
  3,   /* field[3] = quality */
};
static const ProtobufCIntRange blockchain__space_proof__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor blockchain__space_proof__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blockchain.SpaceProof",
  "SpaceProof",
  "Blockchain__SpaceProof",
  "blockchain",
  sizeof(Blockchain__SpaceProof),
  4,
  blockchain__space_proof__field_descriptors,
  blockchain__space_proof__field_indices_by_name,
  1,  blockchain__space_proof__number_ranges,
  (ProtobufCMessageInit) blockchain__space_proof__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blockchain__challenge__field_descriptors[6] =
{
  {
    "challenge_hash",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Challenge, challenge_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prev_block_hash",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Challenge, prev_block_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "challenge_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Challenge, challenge_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_block_height",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Challenge, target_block_height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "issued_at",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Challenge, issued_at),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_difficulty",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Challenge, current_difficulty),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blockchain__challenge__field_indices_by_name[] = {
  0,   /* field[0] = challenge_hash */
  2,   /* field[2] = challenge_id */
  5,   /* field[5] = current_difficulty */
  4,   /* field[4] = issued_at */
  1,   /* field[1] = prev_block_hash */
  3,   /* field[3] = target_block_height */
};
static const ProtobufCIntRange blockchain__challenge__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor blockchain__challenge__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blockchain.Challenge",
  "Challenge",
  "Blockchain__Challenge",
  "blockchain",
  sizeof(Blockchain__Challenge),
  6,
  blockchain__challenge__field_descriptors,
  blockchain__challenge__field_indices_by_name,
  1,  blockchain__challenge__number_ranges,
  (ProtobufCMessageInit) blockchain__challenge__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blockchain__transaction_batch__field_descriptors[2] =
{
  {
    "transactions",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blockchain__TransactionBatch, n_transactions),
    offsetof(Blockchain__TransactionBatch, transactions),
    &blockchain__transaction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__TransactionBatch, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blockchain__transaction_batch__field_indices_by_name[] = {
  1,   /* field[1] = count */
  0,   /* field[0] = transactions */
};
static const ProtobufCIntRange blockchain__transaction_batch__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor blockchain__transaction_batch__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blockchain.TransactionBatch",
  "TransactionBatch",
  "Blockchain__TransactionBatch",
  "blockchain",
  sizeof(Blockchain__TransactionBatch),
  2,
  blockchain__transaction_batch__field_descriptors,
  blockchain__transaction_batch__field_indices_by_name,
  1,  blockchain__transaction_batch__number_ranges,
  (ProtobufCMessageInit) blockchain__transaction_batch__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blockchain__block_list__field_descriptors[2] =
{
  {
    "blocks",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blockchain__BlockList, n_blocks),
    offsetof(Blockchain__BlockList, blocks),
    &blockchain__block__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__BlockList, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blockchain__block_list__field_indices_by_name[] = {
  0,   /* field[0] = blocks */
  1,   /* field[1] = count */
};
static const ProtobufCIntRange blockchain__block_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor blockchain__block_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blockchain.BlockList",
  "BlockList",
  "Blockchain__BlockList",
  "blockchain",
  sizeof(Blockchain__BlockList),
  2,
  blockchain__block_list__field_descriptors,
  blockchain__block_list__field_indices_by_name,
  1,  blockchain__block_list__number_ranges,
  (ProtobufCMessageInit) blockchain__block_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blockchain__pool_status__field_descriptors[2] =
{
  {
    "pending_count",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__PoolStatus, pending_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "confirmed_count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__PoolStatus, confirmed_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blockchain__pool_status__field_indices_by_name[] = {
  1,   /* field[1] = confirmed_count */
  0,   /* field[0] = pending_count */
};
static const ProtobufCIntRange blockchain__pool_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor blockchain__pool_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blockchain.PoolStatus",
  "PoolStatus",
  "Blockchain__PoolStatus",
  "blockchain",
  sizeof(Blockchain__PoolStatus),
  2,
  blockchain__pool_status__field_descriptors,
  blockchain__pool_status__field_indices_by_name,
  1,  blockchain__pool_status__number_ranges,
  (ProtobufCMessageInit) blockchain__pool_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue blockchain__network_message__message_type__enum_values_by_number[11] =
{
  { "UNKNOWN", "BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__UNKNOWN", 0 },
  { "TRANSACTION_SUBMIT", "BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__TRANSACTION_SUBMIT", 1 },
  { "BLOCK_SUBMIT", "BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__BLOCK_SUBMIT", 2 },
  { "CHALLENGE_BROADCAST", "BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__CHALLENGE_BROADCAST", 3 },
  { "PROOF_SUBMIT", "BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__PROOF_SUBMIT", 4 },
  { "BALANCE_REQUEST", "BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__BALANCE_REQUEST", 5 },
  { "BALANCE_RESPONSE", "BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__BALANCE_RESPONSE", 6 },
  { "SYNC_REQUEST", "BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__SYNC_REQUEST", 7 },
  { "SYNC_RESPONSE", "BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__SYNC_RESPONSE", 8 },
  { "ERROR", "BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__ERROR", 9 },
  { "SUCCESS", "BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__SUCCESS", 10 },
};
static const ProtobufCIntRange blockchain__network_message__message_type__value_ranges[] = {
{0, 0},{0, 11}
};
static const ProtobufCEnumValueIndex blockchain__network_message__message_type__enum_values_by_name[11] =
{
  { "BALANCE_REQUEST", 5 },
  { "BALANCE_RESPONSE", 6 },
  { "BLOCK_SUBMIT", 2 },
  { "CHALLENGE_BROADCAST", 3 },
  { "ERROR", 9 },
  { "PROOF_SUBMIT", 4 },
  { "SUCCESS", 10 },
  { "SYNC_REQUEST", 7 },
  { "SYNC_RESPONSE", 8 },
  { "TRANSACTION_SUBMIT", 1 },
  { "UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor blockchain__network_message__message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "blockchain.NetworkMessage.MessageType",
  "MessageType",
  "Blockchain__NetworkMessage__MessageType",
  "blockchain",
  11,
  blockchain__network_message__message_type__enum_values_by_number,
  11,
  blockchain__network_message__message_type__enum_values_by_name,
  1,
  blockchain__network_message__message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor blockchain__network_message__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Blockchain__NetworkMessage, type),
    &blockchain__network_message__message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Blockchain__NetworkMessage, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_message",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Blockchain__NetworkMessage, error_message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blockchain__network_message__field_indices_by_name[] = {
  2,   /* field[2] = error_message */
  1,   /* field[1] = payload */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange blockchain__network_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor blockchain__network_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blockchain.NetworkMessage",
  "NetworkMessage",
  "Blockchain__NetworkMessage",
  "blockchain",
  sizeof(Blockchain__NetworkMessage),
  3,
  blockchain__network_message__field_descriptors,
  blockchain__network_message__field_indices_by_name,
  1,  blockchain__network_message__number_ranges,
  (ProtobufCMessageInit) blockchain__network_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blockchain__wallet__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Wallet, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Wallet, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_key",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Wallet, public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Wallet, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "balance",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Blockchain__Wallet, balance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blockchain__wallet__field_indices_by_name[] = {
  1,   /* field[1] = address */
  4,   /* field[4] = balance */
  0,   /* field[0] = name */
  3,   /* field[3] = nonce */
  2,   /* field[2] = public_key */
};
static const ProtobufCIntRange blockchain__wallet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor blockchain__wallet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blockchain.Wallet",
  "Wallet",
  "Blockchain__Wallet",
  "blockchain",
  sizeof(Blockchain__Wallet),
  5,
  blockchain__wallet__field_descriptors,
  blockchain__wallet__field_indices_by_name,
  1,  blockchain__wallet__number_ranges,
  (ProtobufCMessageInit) blockchain__wallet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blockchain__difficulty_state__field_descriptors[6] =
{
  {
    "current_difficulty",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__DifficultyState, current_difficulty),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "adjustment_interval",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__DifficultyState, adjustment_interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "min_valid_proofs",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__DifficultyState, min_valid_proofs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_valid_proofs",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__DifficultyState, max_valid_proofs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blocks_since_adjust",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__DifficultyState, blocks_since_adjust),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "valid_proofs_count",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Blockchain__DifficultyState, valid_proofs_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blockchain__difficulty_state__field_indices_by_name[] = {
  1,   /* field[1] = adjustment_interval */
  4,   /* field[4] = blocks_since_adjust */
  0,   /* field[0] = current_difficulty */
  3,   /* field[3] = max_valid_proofs */
  2,   /* field[2] = min_valid_proofs */
  5,   /* field[5] = valid_proofs_count */
};
static const ProtobufCIntRange blockchain__difficulty_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor blockchain__difficulty_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blockchain.DifficultyState",
  "DifficultyState",
  "Blockchain__DifficultyState",
  "blockchain",
  sizeof(Blockchain__DifficultyState),
  6,
  blockchain__difficulty_state__field_descriptors,
  blockchain__difficulty_state__field_indices_by_name,
  1,  blockchain__difficulty_state__number_ranges,
  (ProtobufCMessageInit) blockchain__difficulty_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
