/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: blockchain.proto */

#ifndef PROTOBUF_C_blockchain_2eproto__INCLUDED
#define PROTOBUF_C_blockchain_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Blockchain__Transaction Blockchain__Transaction;
typedef struct Blockchain__BlockHeader Blockchain__BlockHeader;
typedef struct Blockchain__Block Blockchain__Block;
typedef struct Blockchain__SpaceProof Blockchain__SpaceProof;
typedef struct Blockchain__Challenge Blockchain__Challenge;
typedef struct Blockchain__TransactionBatch Blockchain__TransactionBatch;
typedef struct Blockchain__BlockList Blockchain__BlockList;
typedef struct Blockchain__PoolStatus Blockchain__PoolStatus;
typedef struct Blockchain__NetworkMessage Blockchain__NetworkMessage;
typedef struct Blockchain__Wallet Blockchain__Wallet;
typedef struct Blockchain__DifficultyState Blockchain__DifficultyState;


/* --- enums --- */

typedef enum _Blockchain__NetworkMessage__MessageType {
  BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__UNKNOWN = 0,
  BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__TRANSACTION_SUBMIT = 1,
  BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__BLOCK_SUBMIT = 2,
  BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__CHALLENGE_BROADCAST = 3,
  BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__PROOF_SUBMIT = 4,
  BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__BALANCE_REQUEST = 5,
  BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__BALANCE_RESPONSE = 6,
  BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__SYNC_REQUEST = 7,
  BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__SYNC_RESPONSE = 8,
  BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__ERROR = 9,
  BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__SUCCESS = 10
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE)
} Blockchain__NetworkMessage__MessageType;

/* --- messages --- */

struct  Blockchain__Transaction
{
  ProtobufCMessage base;
  /*
   * Unique nonce per sender
   */
  uint64_t nonce;
  /*
   * Block height for tx expiry (0 = no expiry)
   */
  uint32_t expiry_block;
  /*
   * 20-byte sender address
   */
  ProtobufCBinaryData source_address;
  /*
   * 20-byte recipient address
   */
  ProtobufCBinaryData dest_address;
  /*
   * Transaction amount
   */
  uint64_t value;
  /*
   * Transaction fee
   */
  uint32_t fee;
  /*
   * 48-byte BLS signature
   */
  ProtobufCBinaryData signature;
};
#define BLOCKCHAIN__TRANSACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blockchain__transaction__descriptor) \
    , 0, 0, {0,NULL}, {0,NULL}, 0, 0, {0,NULL} }


struct  Blockchain__BlockHeader
{
  ProtobufCMessage base;
  /*
   * 32-byte previous block hash
   */
  ProtobufCBinaryData previous_hash;
  /*
   * 32-byte current block hash
   */
  ProtobufCBinaryData hash;
  /*
   * Block height/number
   */
  uint32_t height;
  /*
   * Block creation timestamp
   */
  uint64_t timestamp;
  /*
   * 20-byte farmer address
   */
  ProtobufCBinaryData farmer_address;
  /*
   * Difficulty level (1-256)
   */
  uint32_t difficulty;
  /*
   * 32-byte challenge hash
   */
  ProtobufCBinaryData challenge_hash;
  /*
   * 28-byte winning proof hash
   */
  ProtobufCBinaryData proof_hash;
  /*
   * Winning proof nonce
   */
  uint32_t proof_nonce;
  /*
   * 32-byte proof quality
   */
  ProtobufCBinaryData quality;
  /*
   * Number of transactions
   */
  uint32_t transaction_count;
};
#define BLOCKCHAIN__BLOCK_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blockchain__block_header__descriptor) \
    , {0,NULL}, {0,NULL}, 0, 0, {0,NULL}, 0, {0,NULL}, {0,NULL}, 0, {0,NULL}, 0 }


struct  Blockchain__Block
{
  ProtobufCMessage base;
  Blockchain__BlockHeader *header;
  size_t n_transactions;
  Blockchain__Transaction **transactions;
  /*
   * Sum of all transaction fees
   */
  uint64_t total_fees;
};
#define BLOCKCHAIN__BLOCK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blockchain__block__descriptor) \
    , NULL, 0,NULL, 0 }


struct  Blockchain__SpaceProof
{
  ProtobufCMessage base;
  /*
   * 32-byte plot identifier
   */
  ProtobufCBinaryData plot_id;
  /*
   * Plot entry nonce
   */
  uint32_t nonce;
  /*
   * 28-byte proof hash
   */
  ProtobufCBinaryData proof_hash;
  /*
   * 32-byte quality (distance to target)
   */
  ProtobufCBinaryData quality;
};
#define BLOCKCHAIN__SPACE_PROOF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blockchain__space_proof__descriptor) \
    , {0,NULL}, 0, {0,NULL}, {0,NULL} }


struct  Blockchain__Challenge
{
  ProtobufCMessage base;
  /*
   * 32-byte challenge hash (derived from prev_block_hash)
   */
  ProtobufCBinaryData challenge_hash;
  /*
   * 32-byte hash of the previous block
   */
  ProtobufCBinaryData prev_block_hash;
  /*
   * Challenge sequence number
   */
  uint64_t challenge_id;
  /*
   * Target block height
   */
  uint32_t target_block_height;
  /*
   * Timestamp when issued
   */
  uint64_t issued_at;
  /*
   * Current difficulty (1-256)
   */
  uint32_t current_difficulty;
};
#define BLOCKCHAIN__CHALLENGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blockchain__challenge__descriptor) \
    , {0,NULL}, {0,NULL}, 0, 0, 0, 0 }


struct  Blockchain__TransactionBatch
{
  ProtobufCMessage base;
  size_t n_transactions;
  Blockchain__Transaction **transactions;
  uint32_t count;
};
#define BLOCKCHAIN__TRANSACTION_BATCH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blockchain__transaction_batch__descriptor) \
    , 0,NULL, 0 }


struct  Blockchain__BlockList
{
  ProtobufCMessage base;
  size_t n_blocks;
  Blockchain__Block **blocks;
  uint32_t count;
};
#define BLOCKCHAIN__BLOCK_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blockchain__block_list__descriptor) \
    , 0,NULL, 0 }


struct  Blockchain__PoolStatus
{
  ProtobufCMessage base;
  uint32_t pending_count;
  uint32_t confirmed_count;
};
#define BLOCKCHAIN__POOL_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blockchain__pool_status__descriptor) \
    , 0, 0 }


/*
 * Generic network message wrapper
 */
struct  Blockchain__NetworkMessage
{
  ProtobufCMessage base;
  Blockchain__NetworkMessage__MessageType type;
  /*
   * Serialized inner message
   */
  ProtobufCBinaryData payload;
  /*
   * Error details if type == ERROR
   */
  char *error_message;
};
#define BLOCKCHAIN__NETWORK_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blockchain__network_message__descriptor) \
    , BLOCKCHAIN__NETWORK_MESSAGE__MESSAGE_TYPE__UNKNOWN, {0,NULL}, (char *)protobuf_c_empty_string }


struct  Blockchain__Wallet
{
  ProtobufCMessage base;
  /*
   * Wallet name
   */
  char *name;
  /*
   * 20-byte address
   */
  ProtobufCBinaryData address;
  /*
   * Public key
   */
  ProtobufCBinaryData public_key;
  /*
   * Current transaction nonce
   */
  uint64_t nonce;
  /*
   * Cached balance
   */
  uint64_t balance;
};
#define BLOCKCHAIN__WALLET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blockchain__wallet__descriptor) \
    , (char *)protobuf_c_empty_string, {0,NULL}, {0,NULL}, 0, 0 }


struct  Blockchain__DifficultyState
{
  ProtobufCMessage base;
  /*
   * Current difficulty (1-256)
   */
  uint32_t current_difficulty;
  /*
   * Blocks between adjustments
   */
  uint32_t adjustment_interval;
  /*
   * Min proofs threshold
   */
  uint32_t min_valid_proofs;
  /*
   * Max proofs threshold
   */
  uint32_t max_valid_proofs;
  /*
   * Counter
   */
  uint32_t blocks_since_adjust;
  /*
   * Proofs this round
   */
  uint32_t valid_proofs_count;
};
#define BLOCKCHAIN__DIFFICULTY_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blockchain__difficulty_state__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


/* Blockchain__Transaction methods */
void   blockchain__transaction__init
                     (Blockchain__Transaction         *message);
size_t blockchain__transaction__get_packed_size
                     (const Blockchain__Transaction   *message);
size_t blockchain__transaction__pack
                     (const Blockchain__Transaction   *message,
                      uint8_t             *out);
size_t blockchain__transaction__pack_to_buffer
                     (const Blockchain__Transaction   *message,
                      ProtobufCBuffer     *buffer);
Blockchain__Transaction *
       blockchain__transaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blockchain__transaction__free_unpacked
                     (Blockchain__Transaction *message,
                      ProtobufCAllocator *allocator);
/* Blockchain__BlockHeader methods */
void   blockchain__block_header__init
                     (Blockchain__BlockHeader         *message);
size_t blockchain__block_header__get_packed_size
                     (const Blockchain__BlockHeader   *message);
size_t blockchain__block_header__pack
                     (const Blockchain__BlockHeader   *message,
                      uint8_t             *out);
size_t blockchain__block_header__pack_to_buffer
                     (const Blockchain__BlockHeader   *message,
                      ProtobufCBuffer     *buffer);
Blockchain__BlockHeader *
       blockchain__block_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blockchain__block_header__free_unpacked
                     (Blockchain__BlockHeader *message,
                      ProtobufCAllocator *allocator);
/* Blockchain__Block methods */
void   blockchain__block__init
                     (Blockchain__Block         *message);
size_t blockchain__block__get_packed_size
                     (const Blockchain__Block   *message);
size_t blockchain__block__pack
                     (const Blockchain__Block   *message,
                      uint8_t             *out);
size_t blockchain__block__pack_to_buffer
                     (const Blockchain__Block   *message,
                      ProtobufCBuffer     *buffer);
Blockchain__Block *
       blockchain__block__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blockchain__block__free_unpacked
                     (Blockchain__Block *message,
                      ProtobufCAllocator *allocator);
/* Blockchain__SpaceProof methods */
void   blockchain__space_proof__init
                     (Blockchain__SpaceProof         *message);
size_t blockchain__space_proof__get_packed_size
                     (const Blockchain__SpaceProof   *message);
size_t blockchain__space_proof__pack
                     (const Blockchain__SpaceProof   *message,
                      uint8_t             *out);
size_t blockchain__space_proof__pack_to_buffer
                     (const Blockchain__SpaceProof   *message,
                      ProtobufCBuffer     *buffer);
Blockchain__SpaceProof *
       blockchain__space_proof__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blockchain__space_proof__free_unpacked
                     (Blockchain__SpaceProof *message,
                      ProtobufCAllocator *allocator);
/* Blockchain__Challenge methods */
void   blockchain__challenge__init
                     (Blockchain__Challenge         *message);
size_t blockchain__challenge__get_packed_size
                     (const Blockchain__Challenge   *message);
size_t blockchain__challenge__pack
                     (const Blockchain__Challenge   *message,
                      uint8_t             *out);
size_t blockchain__challenge__pack_to_buffer
                     (const Blockchain__Challenge   *message,
                      ProtobufCBuffer     *buffer);
Blockchain__Challenge *
       blockchain__challenge__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blockchain__challenge__free_unpacked
                     (Blockchain__Challenge *message,
                      ProtobufCAllocator *allocator);
/* Blockchain__TransactionBatch methods */
void   blockchain__transaction_batch__init
                     (Blockchain__TransactionBatch         *message);
size_t blockchain__transaction_batch__get_packed_size
                     (const Blockchain__TransactionBatch   *message);
size_t blockchain__transaction_batch__pack
                     (const Blockchain__TransactionBatch   *message,
                      uint8_t             *out);
size_t blockchain__transaction_batch__pack_to_buffer
                     (const Blockchain__TransactionBatch   *message,
                      ProtobufCBuffer     *buffer);
Blockchain__TransactionBatch *
       blockchain__transaction_batch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blockchain__transaction_batch__free_unpacked
                     (Blockchain__TransactionBatch *message,
                      ProtobufCAllocator *allocator);
/* Blockchain__BlockList methods */
void   blockchain__block_list__init
                     (Blockchain__BlockList         *message);
size_t blockchain__block_list__get_packed_size
                     (const Blockchain__BlockList   *message);
size_t blockchain__block_list__pack
                     (const Blockchain__BlockList   *message,
                      uint8_t             *out);
size_t blockchain__block_list__pack_to_buffer
                     (const Blockchain__BlockList   *message,
                      ProtobufCBuffer     *buffer);
Blockchain__BlockList *
       blockchain__block_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blockchain__block_list__free_unpacked
                     (Blockchain__BlockList *message,
                      ProtobufCAllocator *allocator);
/* Blockchain__PoolStatus methods */
void   blockchain__pool_status__init
                     (Blockchain__PoolStatus         *message);
size_t blockchain__pool_status__get_packed_size
                     (const Blockchain__PoolStatus   *message);
size_t blockchain__pool_status__pack
                     (const Blockchain__PoolStatus   *message,
                      uint8_t             *out);
size_t blockchain__pool_status__pack_to_buffer
                     (const Blockchain__PoolStatus   *message,
                      ProtobufCBuffer     *buffer);
Blockchain__PoolStatus *
       blockchain__pool_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blockchain__pool_status__free_unpacked
                     (Blockchain__PoolStatus *message,
                      ProtobufCAllocator *allocator);
/* Blockchain__NetworkMessage methods */
void   blockchain__network_message__init
                     (Blockchain__NetworkMessage         *message);
size_t blockchain__network_message__get_packed_size
                     (const Blockchain__NetworkMessage   *message);
size_t blockchain__network_message__pack
                     (const Blockchain__NetworkMessage   *message,
                      uint8_t             *out);
size_t blockchain__network_message__pack_to_buffer
                     (const Blockchain__NetworkMessage   *message,
                      ProtobufCBuffer     *buffer);
Blockchain__NetworkMessage *
       blockchain__network_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blockchain__network_message__free_unpacked
                     (Blockchain__NetworkMessage *message,
                      ProtobufCAllocator *allocator);
/* Blockchain__Wallet methods */
void   blockchain__wallet__init
                     (Blockchain__Wallet         *message);
size_t blockchain__wallet__get_packed_size
                     (const Blockchain__Wallet   *message);
size_t blockchain__wallet__pack
                     (const Blockchain__Wallet   *message,
                      uint8_t             *out);
size_t blockchain__wallet__pack_to_buffer
                     (const Blockchain__Wallet   *message,
                      ProtobufCBuffer     *buffer);
Blockchain__Wallet *
       blockchain__wallet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blockchain__wallet__free_unpacked
                     (Blockchain__Wallet *message,
                      ProtobufCAllocator *allocator);
/* Blockchain__DifficultyState methods */
void   blockchain__difficulty_state__init
                     (Blockchain__DifficultyState         *message);
size_t blockchain__difficulty_state__get_packed_size
                     (const Blockchain__DifficultyState   *message);
size_t blockchain__difficulty_state__pack
                     (const Blockchain__DifficultyState   *message,
                      uint8_t             *out);
size_t blockchain__difficulty_state__pack_to_buffer
                     (const Blockchain__DifficultyState   *message,
                      ProtobufCBuffer     *buffer);
Blockchain__DifficultyState *
       blockchain__difficulty_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blockchain__difficulty_state__free_unpacked
                     (Blockchain__DifficultyState *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Blockchain__Transaction_Closure)
                 (const Blockchain__Transaction *message,
                  void *closure_data);
typedef void (*Blockchain__BlockHeader_Closure)
                 (const Blockchain__BlockHeader *message,
                  void *closure_data);
typedef void (*Blockchain__Block_Closure)
                 (const Blockchain__Block *message,
                  void *closure_data);
typedef void (*Blockchain__SpaceProof_Closure)
                 (const Blockchain__SpaceProof *message,
                  void *closure_data);
typedef void (*Blockchain__Challenge_Closure)
                 (const Blockchain__Challenge *message,
                  void *closure_data);
typedef void (*Blockchain__TransactionBatch_Closure)
                 (const Blockchain__TransactionBatch *message,
                  void *closure_data);
typedef void (*Blockchain__BlockList_Closure)
                 (const Blockchain__BlockList *message,
                  void *closure_data);
typedef void (*Blockchain__PoolStatus_Closure)
                 (const Blockchain__PoolStatus *message,
                  void *closure_data);
typedef void (*Blockchain__NetworkMessage_Closure)
                 (const Blockchain__NetworkMessage *message,
                  void *closure_data);
typedef void (*Blockchain__Wallet_Closure)
                 (const Blockchain__Wallet *message,
                  void *closure_data);
typedef void (*Blockchain__DifficultyState_Closure)
                 (const Blockchain__DifficultyState *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor blockchain__transaction__descriptor;
extern const ProtobufCMessageDescriptor blockchain__block_header__descriptor;
extern const ProtobufCMessageDescriptor blockchain__block__descriptor;
extern const ProtobufCMessageDescriptor blockchain__space_proof__descriptor;
extern const ProtobufCMessageDescriptor blockchain__challenge__descriptor;
extern const ProtobufCMessageDescriptor blockchain__transaction_batch__descriptor;
extern const ProtobufCMessageDescriptor blockchain__block_list__descriptor;
extern const ProtobufCMessageDescriptor blockchain__pool_status__descriptor;
extern const ProtobufCMessageDescriptor blockchain__network_message__descriptor;
extern const ProtobufCEnumDescriptor    blockchain__network_message__message_type__descriptor;
extern const ProtobufCMessageDescriptor blockchain__wallet__descriptor;
extern const ProtobufCMessageDescriptor blockchain__difficulty_state__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_blockchain_2eproto__INCLUDED */
